// Example: Simple App generated by MakeaTUI
// This demonstrates the kind of output MakeaTUI generates
package main

import (
	"fmt"
	"os"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
)

// Styles - Ultraviolet theme
var (
	primaryColor   = lipgloss.Color("#9D4EDD")
	secondaryColor = lipgloss.Color("#7B2CBF")
	accentColor    = lipgloss.Color("#E040FB")
	bgColor        = lipgloss.Color("#0D0221")
	surfaceColor   = lipgloss.Color("#1A1333")
	textColor      = lipgloss.Color("#FFFFFF")
	mutedColor     = lipgloss.Color("#6B6B8D")
	borderColor    = lipgloss.Color("#3D2C5E")

	titleStyle = lipgloss.NewStyle().
			Foreground(primaryColor).
			Bold(true).
			MarginBottom(1)

	boxStyle = lipgloss.NewStyle().
			BorderStyle(lipgloss.RoundedBorder()).
			BorderForeground(borderColor).
			Padding(1, 2)

	buttonStyle = lipgloss.NewStyle().
			Background(surfaceColor).
			Foreground(textColor).
			Padding(0, 3).
			BorderStyle(lipgloss.RoundedBorder()).
			BorderForeground(borderColor)

	buttonActiveStyle = lipgloss.NewStyle().
				Background(primaryColor).
				Foreground(textColor).
				Padding(0, 3).
				BorderStyle(lipgloss.RoundedBorder()).
				BorderForeground(accentColor).
				Bold(true)

	statusStyle = lipgloss.NewStyle().
			Background(primaryColor).
			Foreground(textColor).
			Padding(0, 2)
)

type model struct {
	width    int
	height   int
	selected int
	buttons  []string
	quitting bool
}

func initialModel() model {
	return model{
		buttons:  []string{"Start", "Settings", "Help", "Quit"},
		selected: 0,
	}
}

func (m model) Init() tea.Cmd {
	return nil
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.WindowSizeMsg:
		m.width = msg.Width
		m.height = msg.Height

	case tea.KeyMsg:
		switch msg.String() {
		case "q", "ctrl+c":
			m.quitting = true
			return m, tea.Quit
		case "up", "k":
			if m.selected > 0 {
				m.selected--
			}
		case "down", "j":
			if m.selected < len(m.buttons)-1 {
				m.selected++
			}
		case "enter", " ":
			if m.buttons[m.selected] == "Quit" {
				m.quitting = true
				return m, tea.Quit
			}
		}
	}
	return m, nil
}

func (m model) View() string {
	if m.quitting {
		return lipgloss.NewStyle().Foreground(primaryColor).Render("\n  ✨ Goodbye!\n\n")
	}

	// Title
	title := titleStyle.Render("✨ My Glamorous App")

	// Button list
	var buttons string
	for i, btn := range m.buttons {
		if i == m.selected {
			buttons += buttonActiveStyle.Render("▸ "+btn) + "\n"
		} else {
			buttons += buttonStyle.Render("  "+btn) + "\n"
		}
	}

	// Main content box
	content := boxStyle.Width(40).Render(title + "\n\n" + buttons)

	// Status bar
	status := statusStyle.Width(m.width).Render(
		fmt.Sprintf(" MakeaTUI Example │ ↑↓ Navigate │ Enter Select │ q Quit "),
	)

	// Center the content
	centered := lipgloss.Place(
		m.width,
		m.height-1,
		lipgloss.Center,
		lipgloss.Center,
		content,
	)

	return centered + "\n" + status
}

func main() {
	p := tea.NewProgram(initialModel(), tea.WithAltScreen())
	if _, err := p.Run(); err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}
}

